[project]
name = "unknown-unknowns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "h5py>=3.12.1",
    "lightning>=2.5.0.post0",
    "matplotlib>=3.9.4",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.0",
    "scipy>=1.13.1",
    "tensorboard>=2.18.0",
    "tensorboardx>=2.6.2.2",
    "torch>=2.5.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
